server:
  port: 8090

spring:
  application:
    name: multiple-db-drivers-property-source-yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #ddl-auto: update
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update

